In [2]:
from osgeo import gdal
from osgeo import osr
from osgeo import gdal_array
from osgeo import gdalconst

In [8]:
import sys
sys.path.append(r'C:\Program Files\QGIS 3.12\apps\Python37\Scripts')
import gdal_merge as gm

In [73]:
import glob
for i in [10, 20, 60]:
    path = 'A:\lab4\S2A_MSIL2A_20190821T085601_N0213_R007_T36UUA_20190821T115206.SAFE\GRANULE\L2A_T36UUA_A021740_20190821T085815\IMG_DATA\R{}m\\'.format(i)
    in1 = glob.glob(str(path)+'*B02_{}m.jp2'.format(i))
    in2 = glob.glob(str(path)+'*B03_{}m.jp2'.format(i))
    in3 = glob.glob(str(path)+'*B04_{}m.jp2'.format(i))
    in4 = glob.glob(str(path)+'*_*_*8*_{}m.jp2'.format(i))
    gm.main(['', '-separate', '-o', '1AR{}.tif'.format(i), in1[0], in2[0], in3[0], in4[0]])

In [74]:
gdal.Info(gdal.Open('1AR10.tif'))

'Driver: GTiff/GeoTIFF\nFiles: 1AR10.tif\nSize is 10980, 10980\nCoordinate System is:\nPROJCRS["WGS 84 / UTM zone 36N",\n    BASEGEOGCRS["WGS 84",\n        DATUM["World Geodetic System 1984",\n            ELLIPSOID["WGS 84",6378137,298.257223563,\n                LENGTHUNIT["metre",1]]],\n        PRIMEM["Greenwich",0,\n            ANGLEUNIT["degree",0.0174532925199433]],\n        ID["EPSG",4326]],\n    CONVERSION["UTM zone 36N",\n        METHOD["Transverse Mercator",\n            ID["EPSG",9807]],\n        PARAMETER["Latitude of natural origin",0,\n            ANGLEUNIT["degree",0.0174532925199433],\n            ID["EPSG",8801]],\n        PARAMETER["Longitude of natural origin",33,\n            ANGLEUNIT["degree",0.0174532925199433],\n            ID["EPSG",8802]],\n        PARAMETER["Scale factor at natural origin",0.9996,\n            SCALEUNIT["unity",1],\n            ID["EPSG",8805]],\n        PARAMETER["False easting",500000,\n            LENGTHUNIT["metre",1],\n            ID["EPS

In [75]:
gdalData = gdal.Open('1AR10.tif')
print(gdalData.RasterCount)

4


In [81]:
for i in [10, 20, 60]:
    path = 'A:\lab4\S2A_MSIL2A_20190821T085601_N0213_R007_T36UUB_20190821T115206.SAFE\GRANULE\L2A_T36UUB_A021740_20190821T085815\IMG_DATA\R{}m\\'.format(i)
    in1 = glob.glob(str(path)+'*B02_{}m.jp2'.format(i))
    in2 = glob.glob(str(path)+'*B03_{}m.jp2'.format(i))
    in3 = glob.glob(str(path)+'*B04_{}m.jp2'.format(i))
    in4 = glob.glob(str(path)+'*_*_*8*_{}m.jp2'.format(i))
    gm.main(['', '-separate', '-o', '2AR{}.tif'.format(i), in1[0], in2[0], in3[0], in4[0]])

In [82]:
gdalData = gdal.Open('2AR20.tif')
print(gdalData.RasterCount)

4


In [86]:
for i in [1, 2, 6]:
    gdal.Warp('1PAR{}0.tif'.format(i),'1AR{}0.tif'.format(i),dstSRS="EPSG:4326")

In [87]:
for i in [1, 2, 6]:
    gdal.Warp('2PAR{}0.tif'.format(i),'2AR{}0.tif'.format(i),dstSRS="EPSG:4326")

In [88]:
gdal.Warp('AllInOne.tif', ['1PAR10.tif', '1PAR20.tif', '1PAR60.tif', '2PAR10.tif', '2PAR20.tif', '2PAR60.tif'])

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x0000022E9E1C3180> >

In [93]:
gdal.Warp('WrapedImg.tif', 'AllInOne.tif', format = 'GTiff', cutlineDSName='Kyiv_regions.shp', cutlineLayer = 'extent',
              cropToCutline = True, dstNodata = 0)

In [94]:
import numpy as np
obj = (gdal.Open('WrapedImg.tif')).ReadAsArray().astype(np.float32)

In [23]:
print(obj)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [26]:
obj1 = (gdal.Open(in1[0])).ReadAsArray().astype(np.float32)

In [27]:
print(obj1)

[[399. 406. 399. ... 278. 335. 334.]
 [422. 471. 445. ... 279. 304. 271.]
 [440. 471. 452. ... 226. 233. 197.]
 ...
 [492. 491. 458. ... 228. 198. 237.]
 [466. 469. 468. ... 243. 234. 234.]
 [443. 462. 470. ... 214. 221. 243.]]


In [30]:
obj2 = gdal.Open('2AR10.tif').ReadAsArray().astype(np.float32)

In [31]:
obj2

array([[[ 399.,  406.,  399., ...,  278.,  335.,  334.],
        [ 422.,  471.,  445., ...,  279.,  304.,  271.],
        [ 440.,  471.,  452., ...,  226.,  233.,  197.],
        ...,
        [ 492.,  491.,  458., ...,  228.,  198.,  237.],
        [ 466.,  469.,  468., ...,  243.,  234.,  234.],
        [ 443.,  462.,  470., ...,  214.,  221.,  243.]],

       [[ 762.,  769.,  791., ...,  534.,  557.,  583.],
        [ 733.,  784.,  793., ...,  558.,  541.,  506.],
        [ 745.,  784.,  763., ...,  506.,  442.,  385.],
        ...,
        [ 711.,  720.,  709., ...,  516.,  532.,  523.],
        [ 680.,  688.,  714., ...,  536.,  578.,  593.],
        [ 667.,  677.,  677., ...,  561.,  644.,  582.]],

       [[ 586.,  631.,  664., ...,  514.,  702.,  740.],
        [ 639.,  722.,  723., ...,  529.,  692.,  617.],
        [ 690.,  743.,  694., ...,  486.,  541.,  462.],
        ...,
        [ 855.,  869.,  869., ...,  400.,  418.,  438.],
        [ 848.,  857.,  836., ...,  436.,  45

In [ ]:
def normalize(array):
    """Normalizes numpy arrays into scale 0.0 - 1.0"""
    array_min, array_max = array.min(), array.max()
    return ((array - array_min)/(array_max - array_min))
